### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/czatrepajr#15]
Prosze zedytowac moj wpis odnosnie TODO
Magic pls nie szalej z tymi PR
1 feature = 1 branch 
a pozniej zrobi się PR.

### Chat - silnik.
- [x] Działający system wysyłania i pobierania wiadomości
- [x] Refactoring kodu
- [x] Testowanie kodu na różnych przeglądarkach

### Styl Chatu 
- [x] Odpowiednie tagi html.
- [x] Po wysłaniu wiadomości niech input dalej będzie aktywny.

**Comment by Comandeer** [comment]
@efiku co ulepszyłbym? Wszystko… ;) Ale niestety w tej chwili nie mam czasu pisać dokładnie co. Jak się wygrzebię, to dzisiaj wieczorem może to ogarnę

**Comment by efiku** [comment]
Dziękuję serdecznie. Jakiś commit byłby mile widziany ;)
